#!/usr/bin/env python3
"""The aggregation-gain table: the abstract's headline numbers, findable in the paper.

    python3 scripts/build_gain_table.py

Gain = aggregator R@1 minus best single-modality pathway R@1, both from the SAME eval log
of the SAME checkpoint. The abstract cites 'as much as -27.6 R@1' -- that number (PMRL on
VATEX) and every other gain the prose mentions must appear in a table a reader can find.

  table_gain.tex       MAIN: gain per method x benchmark, plus the uniform-weights SCA
                       ablation row that isolates query conditioning as the mechanism.
  table_gain_supp.tex  SUPPLEMENT: the components -- best pathway, aggregator, gain --
                       so the subtraction is checkable.

Sources are the committed harvest extractions (regenerated by harvest_and_push.sh before
this runs), one per provenance:
  GRAM released ckpt   raw_vs_itm_missing.txt  gram_<bench>_r00 pivot rows (r=0 = standard)
  PMRL released ckpt   pmrl_released.txt       authors'-code parse blocks
  HyperGRAM authors    hypergram_authors.txt   authors'-code parse blocks
  SCA T9 (query-w)     raw_vs_itm_frames.txt   t9_qweight_only_<bench> pivot rows
  SCA uniform (b1)     raw_vs_itm_final.txt    b1_bs128_r8_<bench> pivot rows
Anything unparsed prints MISSING and exits 1 -- never a remembered number.
"""
import glob
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from paper_notes import VATEX_NOTE, METHOD                               # noqa: E402

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
HARVEST = os.path.join(ROOT, 'experiments/results/harvest')
BENCHES = ('msrvtt', 'didemo', 'activitynet', 'vatex', 'audiocaps')
LABEL = {'msrvtt': 'MSR-VTT', 'didemo': 'DiDeMo', 'activitynet': 'ActivityNet',
         'vatex': 'VATEX', 'audiocaps': 'AudioCaps'}

_PIVOT = re.compile(r'^(\S+)\s+((?:[-+]?\d+\.\d+\s+){5}[-+]?\d+\.\d+)\s*(?:<-.*)?$')
_AGG = re.compile(r'aggregator \S+ T->V R@1\s+([\d.]+)')
_BEST = re.compile(r'best single pathway (\S+) ([\d.]+)\s+->\s+aggregation (?:gain|tax) ([-+][\d.]+)')


def pivot_cells(txt, prefix):
    """bench -> (best 1mod, aggregator) from a raw_vs_itm pivot file."""
    out = {}
    path = os.path.join(HARVEST, txt)
    if not os.path.exists(path):
        return out
    for line in open(path):
        m = _PIVOT.match(line.rstrip())
        if not m:
            continue
        for b in BENCHES:
            if m.group(1) == '%s_%s' % (prefix, b) or m.group(1) == '%s_%s_r00' % (prefix, b):
                f = [float(x) for x in m.group(2).split()]
                out[b] = (f[2], f[3])          # best 1mod, AGGREG
    return out


def authors_cells(txt):
    """bench -> (best 1mod, aggregator) from a parse_authors_eval harvest file."""
    out = {}
    path = os.path.join(HARVEST, txt)
    if not os.path.exists(path):
        return out
    bench, agg = None, None
    for line in open(path):
        s = line.strip()
        if s.lower() in [b.upper().lower() for b in BENCHES] or s in [b.upper() for b in BENCHES]:
            bench, agg = s.lower(), None
        m = _AGG.search(s)
        if m:
            agg = float(m.group(1))
        m = _BEST.search(s)
        if m and bench in BENCHES and agg is not None:
            out[bench] = (float(m.group(2)), agg)
    return out


ROWS = [
    ('GRAM$^{\\star}$', lambda: pivot_cells('raw_vs_itm_missing.txt', 'gram')),
    ('PMRL$^{\\star}$', lambda: authors_cells('pmrl_released.txt')),
    ('HyperGRAM$^{\\dagger}$', lambda: authors_cells('hypergram_authors.txt')),
    ('%s, uniform weights' % METHOD, lambda: pivot_cells('raw_vs_itm_final.txt', 'b1_bs128_r8')),
    ('\\textbf{%s, query-weighted (ours)}' % METHOD,
     lambda: pivot_cells('raw_vs_itm_frames.txt', 't9_qweight_only')),
]
# HyperGRAM's release does not run the audio-anchor benchmark: '--' by decision.
ABSENT = {('HyperGRAM$^{\\dagger}$', 'audiocaps')}


def main():
    data = {name: fn() for name, fn in ROWS}
    missing = []

    def cell(name, b, kind):
        got = data[name].get(b)
        if got is None:
            if (name, b) in ABSENT:
                return '--'
            missing.append('%s/%s' % (name, b))
            return 'MISSING'
        best, agg = got
        if kind == 'gain':
            g = agg - best
            s = '%+.1f' % g
            return '\\textbf{%s}' % s if g > 0 else s
        return '%.1f & %.1f & %+.1f' % (best, agg, agg - best)

    main_out = [
        '%% Generated by scripts/build_gain_table.py -- do not edit numbers.',
        '%% The abstract\'s "as much as -27.6 R@1" is the PMRL/VATEX cell of THIS table.',
        '\\begin{table}[t]', '\\centering',
        "\\caption{Aggregation gain: each method's joint multimodal score minus its best "
        "single-modality pathway, both within the same embedding (T$\\rightarrow$V R@1; "
        "positive in bold -- fusion adds information, negative -- fusion destroys it). "
        "$\\star$: authors' released checkpoint; $\\dagger$: trained from the authors' "
        "code. The uniform-weights row is our centroid without query conditioning: it pays "
        "the baselines' penalty on the same trunk, isolating query conditioning as the "
        "mechanism -- jointly with masked-view training: trained without masked views, the "
        "query-weighted centroid pays the penalty too (Table~\\ref{tab:loss_ablation}). "
        "These decompositions are not reported in the baselines' papers: both "
        "terms are computed by us from each released model's own embeddings, scored by its "
        "own published scoring function, in one shared evaluation environment. Components "
        "of the subtraction in the supplement. " + VATEX_NOTE + "}",
        '\\label{tab:gain}', '\\small', '\\setlength{\\tabcolsep}{5pt}',
        '\\begin{tabular}{l%s}' % ('c' * len(BENCHES)), '\\toprule',
        'Method & %s \\\\' % ' & '.join(LABEL[b] for b in BENCHES), '\\midrule']
    for name, _ in ROWS[:3]:
        main_out.append('%s & %s \\\\' % (name, ' & '.join(cell(name, b, 'gain')
                                                           for b in BENCHES)))
    main_out.append('\\midrule')
    for name, _ in ROWS[3:]:
        main_out.append('%s & %s \\\\' % (name, ' & '.join(cell(name, b, 'gain')
                                                           for b in BENCHES)))
    main_out += ['\\bottomrule', '\\end{tabular}', '\\end{table}']

    supp_out = [
        '%% Generated by scripts/build_gain_table.py -- do not edit numbers.',
        '\\begin{table*}[t]', '\\centering',
        "\\caption{Components of the aggregation gain (Table~\\ref{tab:gain}): best "
        "single-modality pathway R@1, the method's own aggregate R@1, and their "
        "difference, per benchmark. " + VATEX_NOTE + "}",
        '\\label{tab:gain_components}', '\\small', '\\setlength{\\tabcolsep}{3pt}',
        '\\begin{tabular}{l%s}' % ('ccc' * len(BENCHES)), '\\toprule',
        ' & %s \\\\' % ' & '.join('\\multicolumn{3}{c}{%s}' % LABEL[b] for b in BENCHES),
        ''.join('\\cmidrule(lr){%d-%d}' % (2 + 3 * i, 4 + 3 * i)
                for i in range(len(BENCHES))),
        'Method & %s \\\\' % ' & '.join(['best & agg. & gain'] * len(BENCHES)), '\\midrule']
    for name, _ in ROWS:
        cells = []
        for b in BENCHES:
            c = cell(name, b, 'triple')
            cells.append('-- & -- & --' if c == '--'
                         else ('MISSING & MISSING & MISSING' if c == 'MISSING' else c))
        supp_out.append('%s & %s \\\\' % (name, ' & '.join(cells)))
    supp_out += ['\\bottomrule', '\\end{tabular}', '\\end{table*}']

    for rel, out in (('experiments/results/tables_final/table_gain.tex', main_out),
                     ('experiments/results/tables_final/table_gain_supp.tex', supp_out)):
        path = os.path.join(ROOT, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        open(path, 'w').write('\n'.join(out) + '\n')
        print('wrote %s' % rel)
    if missing:
        seen = sorted(set(missing))
        print('\n%d cell(s) NOT MEASURED -- MISSING printed:' % len(seen), file=sys.stderr)
        for m in seen:
            print('  ' + m, file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
