#!/usr/bin/env python3
"""Appendix table: the modality-subset ladder -- what each added modality is worth.

    python3 scripts/build_subset_table.py

Rows: SCA and the released GRAM checkpoint; columns: the aggregator's own T->V R@1 with
{V}, {V,A}, {V,A,S} on the two three-modality benchmarks. The {V} rung doubles as a wiring
control (a one-element centroid IS the pathway cosine, and a rank-2 'volume' likewise
reduces -- aggregator must equal cos T-V exactly); the {V,A,S} rung is the canonical
main-table cell, never re-run. Cells from the committed harvest pivots (raw_vs_itm_subsets
for tv/tva, the r00 rows of raw_vs_itm_missing for tvas); MISSING + exit 1 for anything
unmeasured.
"""
import glob
import os
import re
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
HARVEST = os.path.join(ROOT, 'experiments/results/harvest')
BENCHES = ('msrvtt', 'vatex')
LABEL = {'msrvtt': 'MSR-VTT', 'vatex': 'VATEX'}
_PIVOT = re.compile(r'^(\S+)\s+((?:[-+]?\d+\.\d+\s+){5}[-+]?\d+\.\d+)\s*(?:<-.*)?$')


def pivot(fname):
    rows = {}
    p = os.path.join(HARVEST, fname)
    if os.path.exists(p):
        for line in open(p):
            m = _PIVOT.match(line.rstrip())
            if m:
                rows[m.group(1)] = [float(x) for x in m.group(2).split()]
    return rows


def main():
    sub = pivot('raw_vs_itm_subsets.txt')
    mis = pivot('raw_vs_itm_missing.txt')
    missing = []

    def agg(model, bench, rung):
        if rung == 'tvas':
            vals = mis.get('%s_%s_r00' % (model, bench))
        else:
            vals = sub.get('%s_%s_%s' % (model, bench, rung))
        if vals is None:
            missing.append('%s/%s/%s' % (model, bench, rung))
            return None
        if rung == 'tv':                       # wiring control: aggregator == cos T-V
            assert abs(vals[3] - vals[0]) < 0.05, \
                '{V} aggregator %.1f != cos T-V %.1f for %s/%s' % (vals[3], vals[0],
                                                                   model, bench)
        return vals[3]

    out = ['%% Generated by scripts/build_subset_table.py -- do not edit numbers.',
           '\\begin{table}[t]', '\\centering',
           "\\caption{The modality-subset ladder: each method's own aggregation score "
           "(T$\\rightarrow$V R@1) as modalities are added at test time, same checkpoints "
           "as the main tables ($\\{V,A,S\\}$ \\emph{is} the main-table cell). Every "
           "modality SCA adds helps or holds; every modality the volume adds hurts -- the "
           "ladder form of the aggregation-gain result (Table~\\ref{tab:gain}). The "
           "$\\{V\\}$ rung is a built-in control: a one-element aggregate equals the "
           "text--video cosine for both geometries, asserted at generation.}",
           '\\label{tab:subset_ladder}', '\\small', '\\setlength{\\tabcolsep}{6pt}',
           '\\begin{tabular}{llccc c}', '\\toprule',
           ' & Method & $\\{V\\}$ & $\\{V,A\\}$ & $\\{V,A,S\\}$ & $\\Delta_{V \\to VAS}$ \\\\',
           '\\midrule']
    for b in BENCHES:
        for i, (name, model) in enumerate((('\\textbf{SCA} (ours)', 'sca'),
                                           ('GRAM$^{\\star}$', 'gram'))):
            cells = [agg(model, b, r) for r in ('tv', 'tva', 'tvas')]
            cs = ['MISSING' if v is None else '%.1f' % v for v in cells]
            d = ('%+.1f' % (cells[2] - cells[0])
                 if cells[0] is not None and cells[2] is not None else 'MISSING')
            out.append('%s & %s & %s & %s \\\\' % (LABEL[b] if i == 0 else '',
                                                   name, ' & '.join(cs), d))
        if b != BENCHES[-1]:
            out.append('\\midrule')
    out += ['\\bottomrule', '\\end{tabular}', '\\end{table}']

    path = os.path.join(ROOT, 'experiments/results/tables_final/table_subset_ladder.tex')
    open(path, 'w').write('\n'.join(out) + '\n')
    print('wrote experiments/results/tables_final/table_subset_ladder.tex')
    if missing:
        print('NOT MEASURED: %s' % ', '.join(missing), file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
