#!/usr/bin/env python3
"""Table 3: retrieval under test-time missing modalities.

    python3 scripts/build_missing_table.py --bench msrvtt
    python3 scripts/build_missing_table.py --all

    Method | Adapter | 0% | 25% | 50% | 75% | 90% | Delta

One row per method, R@1 (the reported two-stage metric) at each mask rate, Delta = the drop
from 0% to 90% -- smaller is better. Cells come from workdir/e1_missing/<model>_<bench>_r<RR>
written by slurm_scripts/missing_eval.sh: the same deterministic per-clip mask for every
method, released checkpoints for the baselines, load-verified where a released checkpoint
runs through our classes.

The 0% column doubles as the control: it is byte-identical to the standard eval path and
must agree with Tables 1/2. HyperGRAM has no row -- its architecture exists only in its own
repository, which has no masking, and its loader drops incomplete clips outright; that is
stated in the caption rather than silently absent.
"""
import argparse
import os
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from raw_vs_itm import scan  # noqa: E402

BENCHES = ('msrvtt', 'didemo', 'activitynet', 'vatex', 'audiocaps')
LABEL = {'msrvtt': 'MSR-VTT', 'didemo': 'DiDeMo', 'activitynet': 'ActivityNet',
         'vatex': 'VATEX', 'audiocaps': 'AudioCaps'}
RATES = ('r00', 'r25', 'r50', 'r75', 'r90')
RATE_LABEL = {'r00': '0\\%', 'r25': '25\\%', 'r50': '50\\%', 'r75': '75\\%', 'r90': '90\\%'}
ROWS = [('\\textbf{SCA} (ours)', 'LoRA', 'sca'),
        ('GRAM$^{\\star}$', 'full-FT', 'gram'),
        ('PMRL$^{\\star}$', 'full-FT', 'pmrl')]


def cell(model, bench, rate):
    d = os.path.join(ROOT, 'workdir/e1_missing', '%s_%s_%s' % (model, bench, rate))
    if not os.path.isdir(d):
        return None
    got, _ = scan(d)
    return got.get('ret_itm_area')


def build(bench, out_path):
    vals = {m: [cell(m, bench, r) for r in RATES] for _, _, m in ROWS}
    missing = ['%s/%s' % (m, r) for _, _, m in ROWS
               for r, v in zip(RATES, vals[m]) if v is None]

    def delta(v):
        return (v[0] - v[-1]) if (v[0] is not None and v[-1] is not None) else None

    colmax = [max((vals[m][i] for _, _, m in ROWS if vals[m][i] is not None), default=None)
              for i in range(len(RATES))]
    deltas = {m: delta(vals[m]) for _, _, m in ROWS}
    dmin = min((d for d in deltas.values() if d is not None), default=None)

    out = []
    out.append('%% Generated by scripts/build_missing_table.py --bench %s -- do not edit.' % bench)
    out.append('%% CONTROL: the 0%% column must equal the %s cells of Tables 1/2.' % LABEL[bench])
    out.append('\\begin{table}[t]')
    out.append('\\centering')
    out.append("\\caption{Text$\\rightarrow$video R@1 on %s when a fraction of gallery clips "
               "lose one modality at test time (identical per-clip masks for all methods; "
               "$\\Delta$ = drop from 0\\%% to 90\\%%, lower is better). $\\star$: authors' "
               "released checkpoint. HyperGRAM cannot be evaluated: its release has no "
               "missing-modality path and its loader discards incomplete clips.}"
               % LABEL[bench])
    out.append('\\label{tab:missing_%s}' % bench)
    out.append('\\small')
    out.append('\\setlength{\\tabcolsep}{5pt}')
    out.append('\\begin{tabular}{llcccccc}')
    out.append('\\toprule')
    out.append('Method & Adapter & %s & $\\Delta$ \\\\'
               % ' & '.join(RATE_LABEL[r] for r in RATES))
    out.append('\\midrule')
    for name, adapter, m in ROWS:
        cells = []
        for i, v in enumerate(vals[m]):
            if v is None:
                cells.append('MISSING')
            else:
                c = '%.1f' % v
                if colmax[i] is not None and abs(v - colmax[i]) < 1e-9:
                    c = '\\textbf{%s}' % c
                cells.append(c)
        d = deltas[m]
        if d is None:
            dc = 'MISSING'
        else:
            dc = '%.1f' % d
            if dmin is not None and abs(d - dmin) < 1e-9:
                dc = '\\textbf{%s}' % dc
        out.append('%s & %s & %s & %s \\\\' % (name, adapter, ' & '.join(cells), dc))
    out.append('\\bottomrule')
    out.append('\\end{tabular}')
    out.append('\\end{table}')

    text = '\n'.join(out) + '\n'
    path = out_path if os.path.isabs(out_path) else os.path.join(ROOT, out_path)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, 'w').write(text)
    print('wrote %s' % out_path)
    if missing:
        print('%s: %d cell(s) NOT MEASURED (MISSING printed): %s'
              % (bench, len(missing), ', '.join(missing[:6])), file=sys.stderr)
    return 1 if missing else 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--bench', choices=BENCHES)
    ap.add_argument('--all', action='store_true')
    ap.add_argument('--out', default=None)
    args = ap.parse_args()
    if args.all:
        rc = 0
        for b in BENCHES:
            rc = max(rc, build(b, 'experiments/results/tables_final/table3_missing_%s.tex' % b))
        return rc
    if not args.bench:
        ap.error('pass --bench or --all')
    return build(args.bench,
                 args.out or 'experiments/results/tables_final/table3_missing_%s.tex' % args.bench)


if __name__ == '__main__':
    sys.exit(main())
