#!/usr/bin/env python3
"""Table 4: the objective, one component removed at a time -- all at the reported T9 recipe.

    python3 scripts/build_loss_ablation_table.py
    python3 scripts/build_loss_ablation_table.py --out experiments/results/tables_final/table4_loss_ablation.tex

Every arm is T9 with exactly one knob changed, so a row's delta is that component's
contribution and nothing else. L_align is never removed: it IS the retrieval objective (a
model trained without it has nothing to retrieve with), so the ablation covers the removable
terms only:

    t9_qweight_only    full objective (the reported configuration; reference row)
    g11_train_nomask   masked training OFF (mask_p_full=1: no masked view is ever drawn,
                       L_align sees only full-arity centroids; l_mask is identically zero)
    g10_mask0          L_mask agreement term OFF (beta=0; masked views still train L_align)
    g8_sem0            L_sem OFF (alpha=0)
    g9_concept0        L_concept OFF (delta=0)
    g6_lambda0         L_unif OFF (lambda=0)

g10 vs g11 is deliberate: together they separate WHERE masking earns its keep -- drawing
masked views for the main loss (g11 removes that) vs the explicit cross-arity agreement
penalty on top (g10 removes only that).

Cells are workdir/e1_frames/<arm>_<bench>, the same directory and the same extraction
(build_paper_table.cell_metrics) as the main tables, so a number cannot differ between
tables. Reported metric: two-stage T->V R@1. Absent cell prints MISSING, never a remembered
number. Delta-bar = mean change vs the full row over the benchmarks both rows have.
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_paper_table import ROOT, LABEL, cell_metrics  # noqa: E402

BENCHES = ('msrvtt', 'didemo', 'activitynet', 'vatex', 'audiocaps')
ROWS = [
    ('full objective (T9)', 't9_qweight_only'),
    ('\\quad w/o masked training views ($p_{\\mathrm{full}}{=}1$)', 'g11_train_nomask'),
    ('\\quad w/o $\\mathcal{L}_{\\mathrm{mask}}$ ($\\beta{=}0$)', 'g10_mask0'),
    ('\\quad w/o $\\mathcal{L}_{\\mathrm{sem}}$ ($\\alpha{=}0$)', 'g8_sem0'),
    ('\\quad w/o $\\mathcal{L}_{\\mathrm{concept}}$ ($\\delta{=}0$)', 'g9_concept0'),
    ('\\quad w/o $\\mathcal{L}_{\\mathrm{unif}}$ ($\\lambda{=}0$)', 'g6_lambda0'),
]


def t2v_r1(arm, bench):
    got = cell_metrics(os.path.join(ROOT, 'workdir/e1_frames', '%s_%s' % (arm, bench)))
    return got[0] if got else None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--out', default='experiments/results/tables_final/table4_loss_ablation.tex')
    args = ap.parse_args()

    vals = {arm: [t2v_r1(arm, b) for b in BENCHES] for _, arm in ROWS}
    full = vals[ROWS[0][1]]
    missing = ['%s/%s' % (arm, b) for _, arm in ROWS
               for b, v in zip(BENCHES, vals[arm]) if v is None]

    def dbar(arm):
        pairs = [(v, f) for v, f in zip(vals[arm], full) if v is not None and f is not None]
        if not pairs:
            return None
        return sum(v - f for v, f in pairs) / len(pairs)

    out = []
    out.append('%% Generated by scripts/build_loss_ablation_table.py -- do not edit numbers.')
    out.append('%% Reference row t9_qweight_only must equal the SCA seed-0 cells behind Tables 1/2.')
    out.append('\\begin{table}[t]')
    out.append('\\centering')
    out.append("\\caption{Ablating the objective at the reported configuration: each row is "
               "T9 with one component removed and nothing else retrained or retuned "
               "(text$\\rightarrow$video R@1, two-stage protocol; $\\bar{\\Delta}$ = mean "
               "change vs.\\ the full objective). $\\mathcal{L}_{\\mathrm{align}}$ is the "
               "retrieval objective itself and is never removed. Removing the masked "
               "training views and removing $\\mathcal{L}_{\\mathrm{mask}}$ are separate "
               "rows: the former stops drawing reduced-arity views for the alignment loss, "
               "the latter drops only the explicit cross-arity agreement term.}")
    out.append('\\label{tab:loss_ablation}')
    out.append('\\small')
    out.append('\\setlength{\\tabcolsep}{4pt}')
    out.append('\\begin{tabular}{l%s c}' % ('c' * len(BENCHES)))
    out.append('\\toprule')
    out.append('Objective & %s & $\\bar{\\Delta}$ \\\\'
               % ' & '.join(LABEL[b] for b in BENCHES))
    out.append('\\midrule')
    for i, (name, arm) in enumerate(ROWS):
        cells = ['MISSING' if v is None else '%.1f' % v for v in vals[arm]]
        if i == 0:
            dc = '--'
        else:
            d = dbar(arm)
            dc = 'MISSING' if d is None else '%+.1f' % d
        out.append('%s & %s & %s \\\\' % (name, ' & '.join(cells), dc))
        if i == 0:
            out.append('\\midrule')
    out.append('\\bottomrule')
    out.append('\\end{tabular}')
    out.append('\\end{table}')

    text = '\n'.join(out) + '\n'
    path = args.out if os.path.isabs(args.out) else os.path.join(ROOT, args.out)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, 'w').write(text)
    print('wrote %s' % args.out)
    if missing:
        print('\n%d cell(s) NOT MEASURED -- MISSING printed:' % len(missing), file=sys.stderr)
        for m in missing:
            print('  ' + m, file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
