#!/usr/bin/env python3
"""Table 2: the four transfer benchmarks side by side, text->video R@1 and R@10.

    python3 scripts/build_transfer_table.py
    python3 scripts/build_transfer_table.py --out experiments/results/tables_final/table2_transfer.tex

MSR-VTT gets the detailed both-directions table (build_paper_table.py); this one puts
DiDeMo, ActivityNet, VATEX and AudioCaps in a single table* with the same sections, the same
rows and the same markers. Every number comes through the SAME extraction functions as the
per-benchmark tables (gram_cell / authors_metrics / sca_cell from build_paper_table), so the
two tables cannot disagree about a value.

Row provenance is the project policy: GRAM* and PMRL* are their authors' released
checkpoints evaluated here; HyperGRAM+ is trained from the authors' unmodified code at their
published recipe; SCA is T9 over three seeds. Published numbers appear only in the
foundation block. HyperGRAM/AudioCaps prints '--' deliberately (their release does not run
the audio-anchor benchmark; their paper reports no AudioCaps number).
"""
import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from paper_notes import VATEX_NOTE, METHOD                               # noqa: E402
from build_paper_table import (ROOT, LABEL, FOUNDATION, _pub, fmt,          # noqa: E402
                               gram_cell, sca_cell, authors_metrics, trainable_col,
                               cell_metrics)

T2_BENCHES = ('didemo', 'activitynet', 'vatex', 'audiocaps')
NCOL = 3 + 2 * len(T2_BENCHES)   # Method | Trainable | Mask | (R@1, R@10) per benchmark


def measured_for(b):
    gram, gram_src = gram_cell(b)
    sca, sca_sd, seeds = sca_cell(b)
    return {'gram': gram, 'gram_src': gram_src,
            'hg': authors_metrics(os.path.join(ROOT, 'workdir/hgeval', b, 'run.log')),
            'pmrl': authors_metrics(os.path.join(ROOT, 'workdir/pmrl_released', b, 'run.log')),
            'sca': sca, 'sca_sd': sca_sd, 'seeds': seeds,
            # The full-FT control: T9's exact recipe with use_lora=false (arm f1_t9_fullft).
            # It exists for ALL FIVE benchmarks and the per-benchmark tables already print
            # it. Omitting it here made the transfer table imply the control was run only on
            # MSR-VTT, which understates the result: LoRA beats full fine-tuning on the
            # reported metric on every benchmark, not just one.
            'fullft': cell_metrics(os.path.join(ROOT, 'workdir/e1_frames',
                                                'f1_t9_fullft_%s' % b))}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--out', default='experiments/results/tables_final/table2_transfer.tex')
    args = ap.parse_args()

    pub = json.load(open(os.path.join(ROOT, 'benchmark_eval/published_rows.json')))
    data = {b: measured_for(b) for b in T2_BENCHES}
    missing = []

    # bold = column max over the measured block only (T->V columns: indices 0 and 1)
    colmax = []
    for b in T2_BENCHES:
        for i in (0, 1):
            vals = [data[b][k][i] for k in ('gram', 'hg', 'pmrl', 'sca')
                    if data[b][k] is not None and data[b][k][i] is not None]
            colmax.append(max(vals) if vals else None)

    def row(name, key, with_sd=False):
        cells, ci = [], 0
        for b in T2_BENCHES:
            vals = data[b][key]
            for i in (0, 1):
                if vals is None or vals[i] is None:
                    if key == 'hg' and b == 'audiocaps':
                        cells.append('--')
                    else:
                        missing.append('%s/%s' % (name, b))
                        cells.append('MISSING')
                else:
                    sd = data[b]['sca_sd'][i] if (with_sd and data[b]['sca_sd']) else None
                    cell = fmt(vals[i], sd)
                    if colmax[ci] is not None and abs(vals[i] - colmax[ci]) < 1e-9:
                        cell = '\\textbf{%s}' % cell
                    cells.append(cell)
                ci += 1
        return ' & '.join(cells)

    out = []
    out.append('%% Generated by scripts/build_transfer_table.py -- do not edit numbers.')
    for b in T2_BENCHES:
        out.append('%% %s GRAM source: %s' % (b, data[b]['gram_src']))
        out.append('%% %s SCA seeds (t2v_r1): %s' % (b, data[b]['seeds'][0]))
    out.append('\\begin{table*}[t]')
    out.append('\\centering')
    out.append("\\caption{Zero-shot text-to-video retrieval on the transfer benchmarks. "
               "\\emph{Trainable} states what each row updates: every baseline fully "
               "fine-tunes the shared VAST backbone, so a parameter count is given only for "
               "the rows we trained ourselves and measured. "
               "$\\S$: numbers as published (reference only; not comparable across "
               "environments). $\\star$: the authors' released checkpoint evaluated in our "
               "environment on our protocol. $\\dagger$: trained from the authors' "
               "unmodified code at their published recipe (no checkpoint is released). SCA "
               "is one configuration over three seeds ($\\pm$ sd on R@1). HyperGRAM's "
               "release does not run the audio-anchor benchmark and its paper reports no "
               "AudioCaps number. " + VATEX_NOTE + "}")
    out.append('\\label{tab:transfer}')
    out.append('\\small')
    out.append('\\setlength{\\tabcolsep}{4pt}')
    out.append('\\begin{tabular}{llc%s}' % ('cc' * len(T2_BENCHES)))
    out.append('\\toprule')
    out.append(' & & & %s \\\\' % ' & '.join('\\multicolumn{2}{c}{%s}' % LABEL[b]
                                           for b in T2_BENCHES))
    out.append(''.join('\\cmidrule(lr){%d-%d}' % (4 + 2 * i, 5 + 2 * i)
                       for i in range(len(T2_BENCHES))))
    out.append('Method & Trainable & Mask & %s \\\\'
               % ' & '.join(['R@1 & R@10'] * len(T2_BENCHES)))
    out.append('\\midrule')
    out.append('\\multicolumn{%d}{l}{\\emph{(a) Foundation models}} \\\\' % NCOL)
    for disp, key, adapter in FOUNDATION:
        cells = []
        for b in T2_BENCHES:
            v = _pub(pub, key, b, 't2v')
            cells += ['--' if x is None else '%.1f' % x for x in v]
        out.append('%s$^{\\S}$ & %s & \\xmark & %s \\\\'
                   % (disp, trainable_col('fullft' if adapter == 'full-FT' else 'none'),
                      ' & '.join(cells)))
    out.append('\\midrule')
    out.append('\\multicolumn{%d}{l}{\\emph{(b) Gramian-volume alignment}} \\\\' % NCOL)
    out.append('GRAM$^{\\star}$ & %s & \\xmark & %s \\\\'
               % (trainable_col('fullft'), row('GRAM', 'gram')))
    out.append('HyperGRAM$^{\\dagger}$ & %s & \\xmark & %s \\\\'
               % (trainable_col('fullft'), row('HyperGRAM', 'hg')))
    out.append('\\midrule')
    out.append('\\multicolumn{%d}{l}{\\emph{(c) Leading-eigenvalue alignment}} \\\\' % NCOL)
    out.append('PMRL$^{\\star}$ & %s & \\xmark & %s \\\\'
               % (trainable_col('fullft'), row('PMRL', 'pmrl')))
    out.append('\\midrule')
    out.append('\\multicolumn{%d}{l}{\\emph{(d) Spherical centroid alignment (ours)}} \\\\' % NCOL)
    out.append('\\textbf{' + METHOD + '} (ours) & %s & \\cmark & %s \\\\'
               % (trainable_col('lora', 'sca_t9'), row('SCA', 'sca', with_sd=True)))
    # Printed only once every cell exists, as in the per-benchmark tables: an absent optional
    # control is silence, not MISSING, because the LoRA row above is the reported
    # configuration either way.
    if all(data[bb]['fullft'] for bb in T2_BENCHES):
        out.append(METHOD + ', full-FT (same recipe) & %s & \\cmark & %s \\\\'
                   % (trainable_col('fullft'), row('SCA full-FT', 'fullft')))
    out.append('\\bottomrule')
    out.append('\\end{tabular}')
    out.append('\\end{table*}')

    # FIELD-COUNT GUARD (see build_paper_table.py): a body row with the wrong number of '&'
    # shifts every later cell one column left without any LaTeX error.
    for line in out:
        if not line.endswith('\\\\') or line.lstrip().startswith(('\\multicolumn', '\\cmidrule',
                                                                  '&')):
            continue
        nf = len(line.rsplit('\\\\', 1)[0].split('&'))
        if nf != NCOL:
            sys.exit('FATAL: row has %d fields, expected %d -- a column would shift '
                     'silently:\n  %s' % (nf, NCOL, line))

    text = '\n'.join(out) + '\n'
    path = args.out if os.path.isabs(args.out) else os.path.join(ROOT, args.out)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, 'w').write(text)
    print('wrote %s' % args.out)
    if missing:
        print('\n%d cell(s) NOT MEASURED -- MISSING is printed, never a remembered number:'
              % len(missing), file=sys.stderr)
        for m in missing:
            print('  ' + m, file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
