#!/usr/bin/env python3
"""Assert that every .tex in tables_final/ was emitted by a generator.

    python3 scripts/check_tables_generated.py

WHY THIS EXISTS. A hand-maintained table sitting beside generated ones is how a
stale number survives a sweep: nothing regenerates it, so it silently keeps
whatever it held when someone last edited it, and it looks exactly as
authoritative as the files around it.

That is not hypothetical. Contribution 1 of the first draft read "performance
comparable to full fine-tuning under the same protocol (53.4 vs. 53.5 R@1)".
Both numbers came from a hand-maintained table1_main.tex that was five days
stale, reported a different learning rate as the headline configuration, and
contradicted the paper's own Section 4.1 ("decreases by 4.2 on MSR-VTT") and its
own Table 1 (50.4 vs 54.6). Every generated table was correct.

So the invariant is: everything the paper cites lives in tables_final/, and
everything in tables_final/ carries a '%% Generated by scripts/...' header.
Ungenerated files belong in tables_archive/, which the paper never reads.

Exit 0 if the invariant holds, 1 with a list of offenders otherwise.
"""
import glob
import os
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
FINAL = os.path.join(ROOT, 'experiments/results/tables_final')
ARCHIVE = 'experiments/results/tables_archive'
MARKER = 'Generated by'
HEADER_LINES = 3          # generators write the marker in the first few lines


def main():
    paths = sorted(glob.glob(os.path.join(FINAL, '*.tex')))
    if not paths:
        sys.exit('FATAL: no .tex found in %s -- wrong working directory?'
                 % os.path.relpath(FINAL, ROOT))
    bad = []
    for p in paths:
        with open(p) as fh:
            head = ''.join(fh.readline() for _ in range(HEADER_LINES))
        if MARKER not in head:
            bad.append(os.path.basename(p))

    if bad:
        print('FATAL: %d table(s) in tables_final/ have no generator header.\n'
              % len(bad), file=sys.stderr)
        for b in bad:
            print('    %s' % b, file=sys.stderr)
        print('\nA table the paper may cite must be reproducible from the evaluation\n'
              'logs. Either add a generator that emits it, or move it to %s/\n'
              '(which the paper never reads) and cite the generated table instead.'
              % ARCHIVE, file=sys.stderr)
        return 1

    print('OK: all %d tables in tables_final/ are generator output.' % len(paths))
    return 0


if __name__ == '__main__':
    sys.exit(main())
