#!/bin/bash
# Run every extractor, write the output into the repo, commit and push.
#
#   bash scripts/harvest_and_push.sh
#   bash scripts/harvest_and_push.sh --no-push        # write and commit only
#
# One command instead of five, and the results land as text files on the branch so they can
# be read without pasting terminal output around. Only text is committed -- the feature and
# rerank dumps are hundreds of MB and stay where they are.
#
# Every step runs even if an earlier one fails; a failure is recorded in the file and in
# INDEX.md rather than aborting the harvest, because a partial harvest is still worth having
# and a missing file is indistinguishable from a step that was never run.
set -uo pipefail
cd "$(dirname "$0")/.."
OUT=experiments/results/harvest
mkdir -p "$OUT"

run() {                      # run <name> <description> <command...>
  local name="$1" desc="$2"; shift 2
  local f="$OUT/$name.txt"
  { echo "\$ $*"; echo; } > "$f"
  "$@" >> "$f" 2>&1
  local rc=$?
  echo "  [$name] rc=$rc -> $f"
  # the command itself is already the first line of the output file; keeping it out of the
  # status record avoids a multi-line command breaking the index table
  printf '%s|%s|%s\n' "$name" "$rc" "$desc" >> "$OUT/.status"
  return 0
}

: > "$OUT/.status"
echo "harvesting into $OUT"

run raw_vs_itm "Aggregator vs ITM per cell, plus arm x benchmark pivots" \
    python3 scripts/raw_vs_itm.py --root workdir/e1_zs --pivot

run score_fusion "Candidate recall@k (the ceiling) and the fusion-weight sweep" \
    bash -c 'shopt -s nullglob; f=(workdir/e1_fusion/*/dumps/rerank_*.pt);
             [ ${#f[@]} -gt 0 ] || { echo "no rerank dumps under workdir/e1_fusion"; exit 3; }
             python3 scripts/sweep_score_fusion.py "${f[@]}"'

run training_gaps "Completeness, step continuity, cross-arm uniformity, config drift" \
    python3 scripts/audit_training_gaps.py --workdir_root workdir_pretrain

run modality_arity "Gallery arity at train vs at each benchmark" \
    python3 scripts/audit_modality_arity.py

run query_centroid "Query-weighted centroid vs uniform, tau sweep on cached features" \
    bash -c 'shopt -s nullglob; f=(results/e4_transfer/feats/*.pt);
             [ ${#f[@]} -gt 0 ] || { echo "no feature dumps under results/e4_transfer/feats"; exit 3; }
             python3 scripts/try_query_centroid.py "${f[@]}"'

# Slurm tails: the exit line and the last error, which is where a failed cell shows up
{
  echo "Last lines of the most recent job logs"
  for pat in e1_xenc e1_fusion b_grid e1_zs; do
    for lg in $(ls -t slurm_scripts/logs/${pat}_*.out 2>/dev/null | head -2); do
      echo; echo "===== $lg"; tail -15 "$lg"
    done
  done
} > "$OUT/job_logs.txt" 2>&1
echo "  [job_logs] -> $OUT/job_logs.txt"

{
  echo "# Harvest"
  echo
  echo "Generated by \`scripts/harvest_and_push.sh\`. Each row is one extractor; rc=0 means it"
  echo "ran, any other value means the file records a failure rather than a result."
  echo
  echo '| output | rc | what it answers |'
  echo '|---|---|---|'
  while IFS='|' read -r name rc desc; do
    printf '| [%s](%s.txt) | %s | %s |\n' "$name" "$name" "$rc" "$desc"
  done < "$OUT/.status"
  echo '| [job_logs](job_logs.txt) | - | Tails of the most recent slurm logs |'
  echo
  echo "## Reading order"
  echo
  echo "1. \`training_gaps\` -- if arms are incomplete or non-uniform, nothing below is comparable."
  echo "2. \`score_fusion\` -- \`w=0\` must equal the ITM number in the eval log, or the metric is"
  echo "   wrong. Then \`cand recall@k\`: where it is saturated, the aggregator cannot influence"
  echo "   the reported number at all and only fusion can."
  echo "3. \`raw_vs_itm\` -- the pivots give arm x benchmark for the aggregator score and for the"
  echo "   reported ITM metric. Compare an SCA arm against \`released\` down each column."
  echo "4. \`job_logs\` -- only if something above is missing or failed."
} > "$OUT/INDEX.md"
echo "  [INDEX] -> $OUT/INDEX.md"
rm -f "$OUT/.status"

if [ "${1:-}" = "--no-push" ]; then
  echo "done (not pushed)"; exit 0
fi

BRANCH=$(git rev-parse --abbrev-ref HEAD)
git add "$OUT"
if git diff --cached --quiet; then
  echo "nothing changed -- not committing"; exit 0
fi
git commit -q -m "Harvest: extractor output at $(date -u +%Y-%m-%dT%H:%MZ)"
# Retrying a push unchanged cannot fix the common failure: the branch moved on the remote
# while the harvest was running, so every retry is rejected for the same reason. Rebase onto
# the remote before retrying -- the harvest only ADDS files under experiments/results, so it
# rebases cleanly on anything that does not touch the same file.
for d in 2 4 8 16; do
  git push -u origin "$BRANCH" && { echo "pushed to $BRANCH"; exit 0; }
  echo "push rejected -- rebasing onto origin/$BRANCH and retrying in ${d}s"
  git pull --rebase origin "$BRANCH" || {
    git rebase --abort 2>/dev/null
    echo "FATAL: rebase failed. The results are committed locally on $BRANCH; resolve by" >&2
    echo "       hand with: git pull --rebase origin $BRANCH" >&2
    exit 1; }
  sleep "$d"
done
echo "push failed after retries -- the results are committed locally on $BRANCH" >&2
exit 1
