#!/usr/bin/env python3
"""Prefetch every network-fetched asset SCA needs, for OFFLINE compute nodes.

Leonardo compute nodes have no internet: run this ONCE on a LOGIN node, pointing at a
directory OUTSIDE $HOME (quota!), e.g.:

    python3 scripts/prefetch_models.py --models_dir $WORK_ROOT/sca_models --with-smoke-data

Then on compute nodes (sbatch scripts do this automatically when MODELS_DIR is set):

    export MODELS_DIR=$WORK_ROOT/sca_models
    source $MODELS_DIR/env.sh        # sets HF_HOME + all *_OFFLINE=1 flags

What it fetches / verifies:
  HF cache (-> $MODELS_DIR/hf):
    - sentence-transformers/all-mpnet-base-v2   (S* production builder default)
    - sentence-transformers/all-MiniLM-L6-v2    (A10 / smoke S* builder)
    - openai/clip-vit-base-patch32 + jxie/flickr8k   (only with --with-smoke-data;
      needed by smoke_test.sh stage 2 on an offline node)
  repo-local ./pretrained_weights/ (the paths the trunk hardcodes):
    - bert/bert-base-uncased        (downloaded from HF if missing)
    - clip/EVA01_CLIP_g_14_psz14_s11B.pt  (downloaded from QuanSun/EVA-CLIP if missing;
      2.3 GB -- the evaclip01_giant weight)
    - beats/BEATs_iter3_plus_AS2M.pt      (VERIFIED ONLY: no official HF mirror exists;
      if missing, get it from the official microsoft/unilm BEATs release page. This
      script refuses to pull unverified third-party weight mirrors.)
  $WORK_ROOT (verified only):
    - the VAST starting checkpoint model_step_204994.pt

Every item ends in one of: FETCHED / CACHED / PRESENT / MISSING(action). Exit code is
non-zero if anything REQUIRED for the requested scope is missing after the run.
"""
import os
import sys
import argparse

SBERT_MODELS = ['sentence-transformers/all-mpnet-base-v2',
                'sentence-transformers/all-MiniLM-L6-v2']
SMOKE_MODELS = ['openai/clip-vit-base-patch32']
SMOKE_DATASETS = ['jxie/flickr8k']
BERT_REPO = 'google-bert/bert-base-uncased'
BERT_FILES = ['config.json', 'vocab.txt', 'pytorch_model.bin',
              'tokenizer_config.json', 'tokenizer.json']
EVA_REPO, EVA_FILE = 'QuanSun/EVA-CLIP', 'EVA01_CLIP_g_14_psz14_s11B.pt'
BEATS_OFFICIAL = 'https://github.com/microsoft/unilm/tree/master/beats (official release)'

ENV_SH = """# generated by scripts/prefetch_models.py -- source on OFFLINE compute nodes
export HF_HOME="{models_dir}/hf"
export HF_HUB_OFFLINE=1
export TRANSFORMERS_OFFLINE=1
export HF_DATASETS_OFFLINE=1
"""


def under_home(path):
    home = os.path.realpath(os.path.expanduser('~'))
    return os.path.realpath(path).startswith(home + os.sep)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--models_dir', required=True,
                    help='shared cache dir OUTSIDE $HOME, e.g. $WORK_ROOT/sca_models')
    ap.add_argument('--repo_dir', default='.',
                    help='repo root holding ./pretrained_weights (default: cwd)')
    ap.add_argument('--with-smoke-data', action='store_true',
                    help='also prefetch CLIP-B/32 + Flickr8k for smoke_test.sh stage 2')
    ap.add_argument('--allow-home', action='store_true',
                    help='override the not-under-$HOME check (NOT recommended on Leonardo)')
    args = ap.parse_args()

    if under_home(args.models_dir) and not args.allow_home:
        sys.exit(f'REFUSED: {args.models_dir} is under $HOME (tiny quota on Leonardo). '
                 'Use e.g. $WORK_ROOT/sca_models, or pass --allow-home to override.')
    os.makedirs(args.models_dir, exist_ok=True)
    os.environ['HF_HOME'] = os.path.join(args.models_dir, 'hf')
    # prefetch MUST be online; fail loudly here rather than half-populating the cache
    for flag in ('HF_HUB_OFFLINE', 'TRANSFORMERS_OFFLINE', 'HF_DATASETS_OFFLINE'):
        os.environ.pop(flag, None)

    from huggingface_hub import snapshot_download, hf_hub_download

    failures = []

    def report(name, status):
        print(f'  [{status:>7s}] {name}', flush=True)

    print(f'== HF cache -> {os.environ["HF_HOME"]}')
    # skip alternative-runtime weight copies (onnx/openvino/tf/flax) -- torch only
    skip = ['onnx/*', 'openvino/*', '*.onnx', '*.h5', 'tf_*', 'flax_*', '*.msgpack']
    hf_models = SBERT_MODELS + (SMOKE_MODELS if args.with_smoke_data else [])
    for repo in hf_models:
        try:
            snapshot_download(repo_id=repo, ignore_patterns=skip)
            report(repo, 'FETCHED')
        except Exception as e:
            report(repo, 'MISSING')
            failures.append(f'{repo}: {e}')
    if args.with_smoke_data:
        from datasets import load_dataset
        for d in SMOKE_DATASETS:
            try:
                load_dataset(d)
                report(f'{d} (dataset)', 'FETCHED')
            except Exception as e:
                report(f'{d} (dataset)', 'MISSING')
                failures.append(f'{d}: {e}')

    pw = os.path.join(args.repo_dir, 'pretrained_weights')
    print(f'== trunk weights -> {pw}')

    bert_dir = os.path.join(pw, 'bert', 'bert-base-uncased')
    if os.path.exists(os.path.join(bert_dir, 'pytorch_model.bin')):
        report('bert/bert-base-uncased', 'PRESENT')
    else:
        try:
            os.makedirs(bert_dir, exist_ok=True)
            for f in BERT_FILES:
                hf_hub_download(repo_id=BERT_REPO, filename=f, local_dir=bert_dir)
            report('bert/bert-base-uncased', 'FETCHED')
        except Exception as e:
            report('bert/bert-base-uncased', 'MISSING')
            failures.append(f'bert: {e}')

    eva_path = os.path.join(pw, 'clip', EVA_FILE)
    if os.path.exists(eva_path):
        report(f'clip/{EVA_FILE}', 'PRESENT')
    else:
        try:
            os.makedirs(os.path.dirname(eva_path), exist_ok=True)
            got = hf_hub_download(repo_id=EVA_REPO, filename=EVA_FILE,
                                  local_dir=os.path.dirname(eva_path))
            assert os.path.exists(eva_path), got
            report(f'clip/{EVA_FILE}', 'FETCHED')
        except Exception as e:
            report(f'clip/{EVA_FILE}', 'MISSING')
            failures.append(f'evaclip: {e}')

    beats_path = os.path.join(pw, 'beats', 'BEATs_iter3_plus_AS2M.pt')
    if os.path.exists(beats_path):
        report('beats/BEATs_iter3_plus_AS2M.pt', 'PRESENT')
    else:
        report('beats/BEATs_iter3_plus_AS2M.pt', 'MISSING')
        failures.append(f'BEATs checkpoint not at {beats_path}: no official HF mirror '
                        f'exists and unverified third-party weights are refused -- '
                        f'download it from {BEATS_OFFICIAL} and place it there '
                        f'(or copy it from the existing GRAM/HyperAlign setup).')

    work_root = os.environ.get('WORK_ROOT', '')
    if work_root:
        vast = os.path.join(work_root, 'GRAM/code/pretrained_models/VAST_foundation/'
                                       'pretrain_vast/ckpt/model_step_204994.pt')
        report('VAST model_step_204994.pt', 'PRESENT' if os.path.exists(vast) else 'MISSING')
        if not os.path.exists(vast):
            failures.append(f'VAST ckpt not at {vast} (staged from the GRAM setup)')
    else:
        print('  [  NOTE ] WORK_ROOT unset -> VAST ckpt presence not checked')

    env_path = os.path.join(args.models_dir, 'env.sh')
    with open(env_path, 'w') as f:
        f.write(ENV_SH.format(models_dir=os.path.abspath(args.models_dir)))
    print(f'== wrote {env_path} (source it on offline compute nodes)')

    if failures:
        print('\nUNRESOLVED (fix before submitting jobs):', file=sys.stderr)
        for f in failures:
            print(f'  - {f}', file=sys.stderr)
        sys.exit(1)
    print('\nAll requested assets are in place for offline compute nodes.')


if __name__ == '__main__':
    main()
